# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy source and build config
COPY tsconfig.json .
COPY src ./src

# Install build tools and compile
RUN npm install typescript@^5.8.2 --no-save && npx tsc --project tsconfig.json

# Set execute permissions
RUN chmod +x build/index.js

# Expose no ports since stdio transport
CMD ["node", "build/index.js"]
